apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx     
  ports:
  - protocol: TCP
    port: 8082        
    targetPort: 80   
    nodePort: 30008  #Range: 30000-32767

#Now we can access the service using the node IP and the node port
#But node IP is not static and it can change
#So we need to create a load balancer to distribute the traffic to the nodes
#We can use the cloud provider load balancer or we can use MetalLB
#MetalLB is a load balancer implementation for bare metal Kubernetes clusters, using standard routing protocols.
