#API version is the version of the Kubernetes API that we want to use to create the object.
apiVersion: v1
#Kind is the type of object that we want to create.
kind: Pod
#Metadata contains information that helps identify the object.
metadata:
  namespace: nginx-namespace
  #Name is a unique name of the object.
  name: nginx-pod
  #Labels are key/value pairs that are used to organize and to select subsets of objects.
  labels:
    team: devops
    app: nginx

#Spec is the desired state of the object.
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80